from datetime import datetime

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, HttpUrl

from app.schemas.cases import CaseDetail
from app.schemas.drafts import DocumentDraftRecord
from app.schemas.evidence import EvidencePackRecord


class EvidenceIntakeRequest(BaseModel):
    url: HttpUrl = Field(validation_alias=AliasChoices("url", "sourceUrl"))
    title: str = Field(validation_alias=AliasChoices("title", "pageTitle"))
    captured_at: datetime = Field(alias="capturedAt")
    source: str | None = Field(default=None, validation_alias=AliasChoices("source", "sourceType"))
    page_text: str = Field(default="", alias="pageText")
    html: str = Field(default="", validation_alias=AliasChoices("html", "rawHtml"))
    screenshot_base64: str = Field(default="", alias="screenshotBase64")
    request_id: str = Field(alias="requestId")
    auto_generate_draft: bool = Field(default=True, alias="autoGenerateDraft")
    draft_template_key: str = Field(default="lawyer-letter", alias="draftTemplateKey")

    model_config = ConfigDict(populate_by_name=True, extra="ignore")


class EvidenceIntakeResponse(BaseModel):
    case: CaseDetail
    evidence_pack: EvidencePackRecord
    generated_draft: DocumentDraftRecord | None = None
